services:
  crossbar:
    container_name: crossbar-container
    image: "crossbar-image"
    restart: always
    ports:
      - "8081:8081"
    stdin_open: true
    tty: true
    volumes:
      - ./crossbar/.crossbar/:/node/.crossbar/
      - ./crossbar/backend.py:/node/backend.py

  nxt:
    container_name: nxt
    image: "nxt-image"
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./nxt/cmd/config.yaml:/app/config.yaml
