FROM golang:1.24 AS builder

WORKDIR /app

COPY ./xconn .

RUN make build && strip xconn

FROM ubuntu:22.04

WORKDIR /app

COPY --from=builder /app/xconn /app/

CMD ["./xconn", "--config", "config.yaml"]
