services:
  crossbar:
    container_name: crossbar-container
    image: "crossbar-image"
    restart: always
    ports:
      - "8081:8081"
    stdin_open: true
    tty: true
    volumes:
      - ./crossbar/.crossbar/:/node/.crossbar/
      - ./crossbar/backend.py:/node/backend.py

  xconn:
    container_name: xconn
    image: "xconn-image"
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./xconn/cmd/config.yaml:/app/config.yaml
