services:
  crossbar:
    container_name: crossbar-container
    image: "xconnio/crossbar:latest"
    restart: always
    ports:
      - "8081:8081"
    stdin_open: true
    tty: true
    volumes:
      - ./crossbar/.crossbar/:/node/.crossbar/
      - ./crossbar/backend.py:/node/backend.py

  nxt:
    container_name: nxt
    image: "xconnio/nxt:latest"
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./nxt/cmd/config.yaml:/app/config.yaml
      - /tmp/:/tmp/
    user: "${MY_UID}:${MY_GID}"
    entrypoint: [ "/bin/sh", "-c", "rm -f /tmp/nxt.sock && exec /app/nxt -config /app/config.yaml" ]

  nexus:
    container_name: nexus
    image: "xconnio/nexus:latest"
    restart: always
    ports:
      - "8082:8082"
