version: "3.10"

services:
  crossbar:
    container_name: crossbar-container
    image: "crossbar-image"
    restart: always
    network_mode: host
    stdin_open: true
    tty: true
    ports:
      - "${CROSSBAR_PORT:-8081}:${CROSSBAR_PORT:-8081}"

  xconn:
    container_name: xconn
    image: "xconn-image"
    restart: always
    network_mode: host
    ports:
      - "${XCONN_PORT:-8080}:${XCONN_PORT:-8080}"
