FROM golang:1.23 AS builder

WORKDIR /app

COPY ./xconn .

RUN make build && strip xconn

FROM ubuntu:22.04

WORKDIR /app

COPY --from=builder /app/xconn /app/
COPY --from=builder /app/cmd/config.yaml /app/

CMD ["./xconn", "--config", "config.yaml"]
