version: "3.10"

services:
  crossbar:
    user: root
    container_name: crossbar-container
    image: "crossbario/crossbar"
    restart: always
    network_mode: host
    stdin_open: true
    tty: true
    volumes:
      - ./crossbar/.crossbar/:/node/.crossbar/
      - ./crossbar/backend.py:/node/backend.py

  xconn:
    container_name: xconn
    image: "xconn-image"
    restart: always
    network_mode: host
    volumes:
      - ./xconn/cmd/config.yaml:/app/config.yaml
