lint:
	golangci-lint run

build:
	go build -o nxt github.com/xconnio/xconn-aat-setup/cmd

run:
	go run github.com/xconnio/xconn-aat-setup/cmd

test:
	go test github.com/xconnio/xconn-aat-setup -v -count=1
