name: AAT CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-start-routers:
    uses: ./.github/workflows/start-routers.yaml
    with:
      crossbar_port: "8081"
      xconn_port: "8080"

  test:
    runs-on: ubuntu-latest
    needs: call-start-routers  # Ensures 'call-start-routers' runs first

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Wick
        run: sudo snap install wick --classic

      - name: Test Crossbar
        run: make run-wick-commands url=ws://localhost:8081/ws

      - name: Test XConn
        run: make run-wick-commands url=ws://localhost:8080/ws

      - name: Additional step
        run: echo "This is an additional step after the reusable workflow."
