name: aat CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build nxt docker
        run: make build-docker-nxt

      - name: Build crossbar docker
        run: make build-docker-crossbar

      - name: Run routers
        run: docker compose up -d

      - name: Install wick
        run: sudo snap install wick --classic

      - name: Test crossbar
        run: make run-wick-commands url=ws://localhost:8081/ws

      - name: Test nxt
        run: make run-wick-commands url=ws://localhost:8080/ws
