name: Upload Docker images to docker hub

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build crossbar docker image
        run: docker build -f Dockerfile.crossbar -t xconnio/crossbar:latest .

      - name: Push crossbar docker image
        run: docker push xconnio/crossbar:latest

      - name: Build nxt-router docker image
        run: docker build -f Dockerfile.nxt -t xconnio/nxt:latest .

      - name: Push nxt-router docker image
        run: docker push xconnio/nxt:latest
